/* File generated by helper script from https://github.com/zaydabudayyeh/wave_generator
for use with ECE385 course at the University of Illinois at Urbana Champaign */

module hightom_rom(
input clk,
input [12:0] addr,
output logic [15:0] q
);

logic [15:0] rom [5371];
always_ff @(posedge clk) begin
	q <= rom[addr];
end
initial begin $readmemh("hightom.txt", rom); end
endmodule