/* File generated by helper script from https://github.com/zaydabudayyeh/wave_generator
for use with ECE385 course at the University of Illinois at Urbana Champaign */

module Kick_rom(
input clk,
input [13:0] addr,
output logic [23:0] q
);

logic [23:0] rom [8261];
always_ff @(posedge clk) begin
	q <= rom[addr];
end
initial begin $readmemh("Kick.txt", rom); end
endmodule