/* File generated by helper script from https://github.com/zaydabudayyeh/wave_generator
for use with ECE385 course at the University of Illinois at Urbana Champaign */

module lowtom_rom(
input clk,
input [12:0] addr,
output logic [15:0] q
);

logic [15:0] rom [8131];
always_ff @(posedge clk) begin
	q <= rom[addr];
end
initial begin $readmemh("lowtom.txt", rom); end
endmodule